name: SignEdit
version: "${pom.version}"
author: PetteriM1
main: me.petterim1.signedit.SignEdit
api: ["1.0.0"]

commands:
  signedit:
    permission: signedit
    description: "표지판 수정 모드를 활성화 합니다."
    usage: "/signedit"

permissions:
  signedit:
    default: op
    description: "표지판 수정 모드를 활성화 합니다."
